name: tesis_app_ciclismo_epn
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.3.3 <4.0.0'

dependencies:
  cloud_firestore: ^4.17.0
  firebase_core: ^2.30.0
  flutter:
    sdk: flutter
  flutter_polyline_points: ^2.0.0
  google_maps_flutter: ^2.6.1
  location: ^6.0.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/img/profile.jpg

fonts:
  - family: Lato
    fonts:
      - asset: fonts/Lato/Lato-Regular-ttf